### ISSUE TITLE
Remindme functionality

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#2]

**Comment by LunaUrsa** [comment]
This is completed

![image](https://user-images.githubusercontent.com/1836049/164950670-19e65e0a-1486-4b25-8008-af5719c7638a.png)

**Comment by LunaUrsa** [comment]
This does not work in production because i'm using a JSON file to store reminders. With the way DO works, the JSON file will get overwritten every time i upload a new version, and I don't even think DO allows us to write to a JSON file cuz DO isnt meant to be a database (at least not the app builder).

I'm using the JSON file because otherwise I would need to do an API call every minute to the firebase. That seems....excessive? @derelictions have any thoughts on this?

**Comment by LunaUrsa** [comment]
This has been completed!

![image](https://user-images.githubusercontent.com/1836049/165417371-f47cf939-3575-4c34-823d-6232a16543a7.png)


![Uploading image.png…]()
